#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("BayesWizard.Resource", IsApplication=true)]

namespace BayesWizard
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f050000
			public const int theEvent = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int theTest = 2131034113;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int bubbleleft = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int bubbleright = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Icon = 2130837506;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070005
			public const int askBayes = 2131165189;
			
			// aapt resource value: 0x7f070011
			public const int cont1 = 2131165201;
			
			// aapt resource value: 0x7f070010
			public const int customize = 2131165200;
			
			// aapt resource value: 0x7f070012
			public const int editText1 = 2131165202;
			
			// aapt resource value: 0x7f070003
			public const int heading1 = 2131165187;
			
			// aapt resource value: 0x7f070002
			public const int linearLayout1 = 2131165186;
			
			// aapt resource value: 0x7f07000f
			public const int nintynine1 = 2131165199;
			
			// aapt resource value: 0x7f070009
			public const int priorProbability = 2131165193;
			
			// aapt resource value: 0x7f07000c
			public const int prob1 = 2131165196;
			
			// aapt resource value: 0x7f07000b
			public const int probability = 2131165195;
			
			// aapt resource value: 0x7f070001
			public const int scrollView1 = 2131165185;
			
			// aapt resource value: 0x7f07000e
			public const int seek1 = 2131165198;
			
			// aapt resource value: 0x7f070004
			public const int subHeading1 = 2131165188;
			
			// aapt resource value: 0x7f070007
			public const int theAssumption = 2131165191;
			
			// aapt resource value: 0x7f070000
			public const int toolbar1 = 2131165184;
			
			// aapt resource value: 0x7f07000a
			public const int truePositive = 2131165194;
			
			// aapt resource value: 0x7f070006
			public const int whatsup = 2131165190;
			
			// aapt resource value: 0x7f070008
			public const int withoutTest = 2131165192;
			
			// aapt resource value: 0x7f07000d
			public const int zero1 = 2131165197;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040007
			public const int Iassume = 2130968583;
			
			// aapt resource value: 0x7f040003
			public const int askBayes = 2130968579;
			
			// aapt resource value: 0x7f040008
			public const int because = 2130968584;
			
			// aapt resource value: 0x7f040005
			public const int cont = 2130968581;
			
			// aapt resource value: 0x7f040004
			public const int customizeText = 2130968580;
			
			// aapt resource value: 0x7f040002
			public const int intro = 2130968578;
			
			// aapt resource value: 0x7f040000
			public const int posterior = 2130968576;
			
			// aapt resource value: 0x7f04000e
			public const int truePositive = 2130968590;
			
			// aapt resource value: 0x7f04000f
			public const int truePositive2 = 2130968591;
			
			// aapt resource value: 0x7f040010
			public const int truePositive3 = 2130968592;
			
			// aapt resource value: 0x7f040001
			public const int welcome = 2130968577;
			
			// aapt resource value: 0x7f040006
			public const int whatsup = 2130968582;
			
			// aapt resource value: 0x7f040009
			public const int withoutTest1 = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int withoutTest2 = 2130968586;
			
			// aapt resource value: 0x7f04000b
			public const int withoutTest3 = 2130968587;
			
			// aapt resource value: 0x7f04000c
			public const int withoutTestAnswer = 2130968588;
			
			// aapt resource value: 0x7f04000d
			public const int withoutTestAnswer2 = 2130968589;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int MyTheme = 2131099648;
			
			// aapt resource value: 0x7f060002
			public const int StandardButton = 2131099650;
			
			// aapt resource value: 0x7f060001
			public const int StandardText = 2131099649;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
